---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "github_actions"
      - "no_ci_cd_run"
    commit-message:
      prefix: "chore"
    groups:
      patch-minor-dependencies:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/actions/commitizen-prompt-conventional"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
    commit-message:
      prefix: "chore"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "faker"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "pip"
    directory: "/actions/commitizen"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
    commit-message:
      prefix: "chore"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/actions/commitizen-tools-check"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
    commit-message:
      prefix: "chore"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "gomod"
    directory: "/actions/hardcoding-check"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "github_actions"
      - "no_ci_cd_run"
    commit-message:
      prefix: "chore"
    groups:
      patch-minor-dependencies:
        update-types:
          - "minor"
          - "patch"
