version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "aps831"
    labels:
      - "enhancement"

  - package-ecosystem: "pip"
    directory: "/actions/commitizen"
    schedule:
      interval: "daily"
    assignees:
      - "aps831"
    labels:
      - "enhancement"
