version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "github_actions"
      - "no_ci_cd_run"
  - package-ecosystem: "pip"
    directory: "/actions/commitizen"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
  - package-ecosystem: "pip"
    directory: "/actions/commitizen-tools-check"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
  - package-ecosystem: "npm"
    directory: "/actions/commitizen-prompt-conventional"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
  - package-ecosystem: "gomod"
    directory: "/actions/hardcoding-check"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
      - "no_ci_cd_run"
