version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "github_actions"
  - package-ecosystem: "pip"
    directory: "/actions/commitizen"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
  - package-ecosystem: "gomod"
    directory: "/actions/hardcoding-check"
    schedule:
      interval: "weekly"
    assignees:
      - "aps831"
    labels:
      - "dependencies"
