---
name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0
        with:
          submodules: true
      - name: run tests
        run: .bats/bats/bin/bats bats -r test/
  publish:
    needs: test
    permissions:
      contents: write
      packages: write
    uses: aps831/workflows/.github/workflows/release.yaml@master
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
