---
name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # pin@v4.0.0
        with:
          submodules: true
      - name: run tests
        run: .bats/bats/bin/bats bats -r test/
  publish:
    needs: test
    permissions:
      contents: write
    uses: aps831/workflows/.github/workflows/release.yaml@f98edcf8f4289fe52db780d9757dfe01cecfe630 # pin@master
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
