---
name: Run tests
on:
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # pin@v4.1.5
        with:
          submodules: true
      - name: run tests
        run: .bats/bats/bin/bats -r test/
