---
name: Run tests
on:
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          submodules: true
      - name: run tests
        run: .bats/bats/bin/bats bats -r test/
