---
name: Run tests
on:
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # pin@v4.1.3
        with:
          submodules: true
      - name: run tests
        run: .bats/bats/bin/bats -r test/
