---
name: Run tests
on:
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # pin@v4.1.6
        with:
          submodules: true
      - name: run tests
        run: .bats/bats/bin/bats -r test/
